from typing import Dict, Any

class NetSuiteRecordMapper:
    @staticmethod
    def map_document_to_netsuite(doc_type: str, fields: Dict[str, Any]) -> tuple[str, Dict[str, Any]]:
        """Maps extracted document fields into official NetSuite SuiteTalk REST API JSON record structures."""
        if doc_type in ["BUSINESS_INVOICE", "RECEIPT"]:
            return "vendorBill", {
                "tranId": str(fields.get("invoice_number") or fields.get("receipt_id") or "INV-LOCAL"),
                "entity": {"id": str(fields.get("vendor_id") or "101")},
                "tranDate": fields.get("issue_date") or fields.get("order_date"),
                "dueDate": fields.get("due_date"),
                "memo": f"Automated Vendor Bill created by IntelliParse for {fields.get('vendor', 'Vendor')}",
                "userTotal": float(fields.get("total") or fields.get("subtotal") or 0.0),
                "currency": {"symbol": fields.get("currency", "USD")}
            }

        elif doc_type == "PURCHASE_ORDER":
            return "purchaseOrder", {
                "tranId": str(fields.get("po_number") or "PO-LOCAL"),
                "entity": {"id": str(fields.get("vendor_id") or "101")},
                "tranDate": fields.get("order_date") or fields.get("issue_date"),
                "orderStatus": "B",  # Pending Receipt
                "memo": f"Purchase Order synced from IntelliParse for {fields.get('vendor', 'Vendor')}",
                "total": float(fields.get("total") or 0.0)
            }

        elif doc_type == "SALES_ORDER":
            return "salesOrder", {
                "tranId": str(fields.get("so_number") or "SO-LOCAL"),
                "entity": {"id": str(fields.get("customer_id") or "202")},
                "tranDate": fields.get("order_date"),
                "memo": f"Sales Order created via IntelliParse for {fields.get('customer', 'Customer')}",
                "total": float(fields.get("total") or 0.0)
            }

        elif doc_type == "LEAD":
            return "lead", {
                "companyName": str(fields.get("company") or fields.get("lead_name") or "New Lead"),
                "email": fields.get("email"),
                "phone": fields.get("phone"),
                "leadStatus": {"id": "1"},  # New Inquiry
                "comments": f"CRM Lead generated by IntelliParse AI Agent"
            }

        else:
            return "customRecord", {
                "name": f"{doc_type} - {fields.get('title', 'Document')}",
                "custrecord_extracted_json": fields
            }

netsuite_mapper = NetSuiteRecordMapper()
